# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 61cc54db9edc60c1c0896214588717ee0f253d6219ddbd97cfc8f5049e7be8611c182d078edca560e1645a809c21940233e45239197782edd5f1aad23d368f3f

test:
  secret_key_base: 80ea4ba2a9287b2d62c63caa622f64a445740b9a3d97d88e806d1166d76b8418afa88739b686d5449556ddac0c63619dbf18c64d312d32d4bfea3cdd2ded273d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
