Question.create!(text: 'Do Auth. Just do it.', parent_id: NULL)
Question.create!(text: 'Make the models', parent_id: '1')
Question.create!(text: 'Make the controllers', parent_id: '1')
Question.create!(text: 'Make the views', parent_id: '1')
Question.create!(text: 'Implement session tokens', parent_id: '2')
Question.create!(text: 'Validate proper attributes', parent_id: '2')
Question.create!(text: 'Implement passwords', parent_id: '2')
