Question.create!(text: 'Do Auth. Just do it.', parent_id: nil)
Question.create!(text: 'Make the models', parent_id: '1')
Question.create!(text: 'Implement user migration', parent_id: '2')
Question.create!(text: 'Add username', parent_id: '3')
Question.create!(text: '# in user migration', parent_id: '4')
Question.create!(text: 't.string :username, null: false', parent_id: '4')
Question.create!(text: 'Add password digest', parent_id: '3')
Question.create!(text: '# in user migration', parent_id: '7')
Question.create!(text: '#t.string :password_digest, null: false', parent_id: '7')
Question.create!(text: 'Add session token', parent_id: '3')
Question.create!(text: '# in user migration<br />t.string :session_token, null: false', parent_id: '10')
Question.create!(text: 'Add indexes for session token', parent_id: '3')
Question.create!(text: '# in user migration', parent_id: '12')
Question.create!(text: 'add_index :users, :session_token: unique: true', parent_id: '12')
Question.create!(text: 'Implement session tokens', parent_id: '2')
Question.create!(text: 'Generate session token', parent_id: '15')
Question.create!(text: '# in user model', parent_id: '16')
Question.create!(text: 'def self.generate_session_token', parent_id: '16')
Question.create!(text: '&nbsp;&nbsp;SecureRandom::urlsafe_base64(16)', parent_id: '16')
Question.create!(text: 'end', parent_id: '16')
Question.create!(text: 'Ensure session token', parent_id: '15')
Question.create!(text: '# in user model', parent_id: '21')
Question.create!(text: '# and don\'t forget to call this after initialize', parent_id: '21')
Question.create!(text: 'def ensure_session_token', parent_id: '21')
Question.create!(text: '&nbsp;&nbsp;self.session_token ||= User.generate_session_token', parent_id: '21')
Question.create!(text: 'end', parent_id: '21')
Question.create!(text: 'Reset session token', parent_id: '15')
Question.create!(text: '# in user model', parent_id: '27')
Question.create!(text: 'def reset_session_token!', parent_id: '27')
Question.create!(text: '&nbsp;&nbsp;self.session_token = User.generate_session_token', parent_id: '27')
Question.create!(text: '&nbsp;&nbsp;self.save', parent_id: '27')
Question.create!(text: '&nbsp;&nbsp;self.session_token', parent_id: '27')
Question.create!(text: 'end', parent_id: '27')
Question.create!(text: 'Validate proper attributes', parent_id: '2')
Question.create!(text: '# all in user model', parent_id: '34')
Question.create!(text: 'validates :username, :password_digest, :session_token, presence: true', parent_id: '34')
Question.create!(text: 'validates :password, length: { minimum: 6 }, allow_nil: true', parent_id: '34')
Question.create!(text: 'Implement passwords', parent_id: '2')
Question.create!(text: 'Set the password on the user', parent_id: '38')
Question.create!(text: '# in user model<br />def password=(password)<br />&nbsp;&nbsp;', parent_id: '39')
Question.create!(text: 'Check the password is correct', parent_id: '38')
Question.create!(text: 'Find the user based on credentials', parent_id: '38')
Question.create!(text: '# in user model<br />def self.find_by_credentials(username, password)<br />&nbsp;&nbsp;user = User.find_by(username: username)<br />&nbsp;&nbsp;user && user.is_password?(password) ? user : nil', parent_id: '42')
Question.create!(text: 'Make the controllers', parent_id: '1')
Question.create!(text: 'Create controllers and helpers', parent_id: '44')
Question.create!(text: 'Add helpers', parent_id: '45')
Question.create!(text: 'Create proper controllers', parent_id: '45')
Question.create!(text: 'Add sign up functionality', parent_id: '44')
Question.create!(text: 'Add new method in user controller', parent_id: '48')
Question.create!(text: 'Add create method in user controller', parent_id: nil)
Question.create!(text: 'Sign in user on creation', parent_id: '48')
Question.create!(text: 'Add log in functionality', parent_id: '44')
Question.create!(text: 'Sign in user', parent_id: '52')
Question.create!(text: 'Add new method to session', parent_id: '52')
Question.create!(text: 'Add create method to session', parent_id: '52')
Question.create!(text: 'Add sign out functionality', parent_id: '44')
Question.create!(text: 'Sign out user', parent_id: '56')
Question.create!(text: 'Destroy user session', parent_id: '56')
Question.create!(text: 'Make the views', parent_id: '1')
Question.create!(text: 'Add links for login/signin/signout', parent_id: '59')
Question.create!(text: 'Add generic form for signup/login', parent_id: '59')
Question.create!(text: 'Generate form authentication token', parent_id: '61')
Question.create!(text: 'Ensure the form points to the correct url', parent_id: '61')
Question.create!(text: 'Add error feedback', parent_id: '59')
